[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1m2SZgMap_UpqFDc9anr1Ac6hXPc9u65KZRLTHWZhZtk/edit?usp=sharing"

[connections.postgresql]
dialect = "postgresql"
host = "localhost"
port = "5432"
database = "xxx"
username = "postgres"
password = "123789"

# From your JSON key file
"type": "service_account",
"project_id": "savvy-generator-414408",
"private_key_id": "d1d24df8819d501b7b6bbc111f267308988ee411",
"private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2gHhDiZvRXC6j\nospcY4eMzBrsf596ydVNATwrzOFKCa3Bx/XFQ9joY2ci9CeVm75vYRQ/8tYg1UJ0\nNbmcGiIuUYglhCl7cqvrH3W7D6fHITtUCcIow0CwiQn/DdjoEH1++vP6JyexvF+x\ntCR4BePG1pJ+eAbovgizW4sVSGB8I4rDeZuj7/x09qN4qsqQmSocjuIUuxlPiLZI\ng55zYGbiApe6Wpt+c6WZQP3N5Z5Y5BcOAN2H+SqP36fmjKB6R7xwzQ01x6+k5mlb\nyLuHYoGan85UU4bZzp74BBiO3f9g7p6OQvdx89xOVP2W8+YlQiSY9qJdE1qe309O\nQlV18Dz7AgMBAAECggEAAdUUYAk3qUh1p2rxATB2ofFCq/E0FrWEELvccMwjzux9\n9B4f15UwzlSBKpas9xGTPecJnwK/J6E8g5IuhOS2RyTGayoCiJzEIR41vmUP2C37\nPILEkkgzlBIsKYVoEhxoRiga3v4Zpe0wQMaAPzw/5zUsT1zBJQETcUmQAeyyG0zz\nrBj6yFvq3+8MRKKuFzxegnukAAsplWhxKjwlobQ3dhZRvvUGVxfgxTb1xXRFZRi+\n2K+L9hh2XqYQuNxVzNEadc5+4mhWCGyJwlgnErCw9PvpDvNr8ZeuiaKJI7Z3r/wD\nnH0wFQZTe/ZiPeT6KxX1WRBx28F1I/VE46IFeVeVgQKBgQD374P3MxpZPxbNv2Wo\n/lGz2nkQ/2U9tD6rZzCaRecUZXXwZlhd19S3WnKa8KKBRWsAIidVBQYnbP085RMP\nO4MDf5bl2/cVt+SQuQ4RSiovnAclwhZv59HASUAp7nNXYmBXQXEevRiBspxNzi2q\n/vtz3XX+Zyluhe85Vs24/uRf4QKBgQC8cBttc6yyDXFDj6k5uci6ZpkhWiKlsdg2\n+ChFmOmyE5bVhLrtdYO/6VGBDLXxv2HEqY6VGb0kKbfdznxsOb+OkejZ90wmeBFW\nWNeulHXtvnQSD1QVxcfoSTFYWooDotqw7ZQnNqSwFrcNDMY05mvfBYEPQzabZpcN\nDnHYoKcoWwKBgB5zU0DcDONjJTjVxfWQbpZpQa89vsBqT7wba1O3PB88KtUArN+x\nr1VpjWPMJBk+Xlrg1vXRLSVQdHWzKLkZNQkL9Yt7jYgkUrUXlUu4USARyKrxgHH0\nBcXY+UFtIMtdsLlmty7wSH89YYcIyIEU2essCt7Y6rTBTFU9fPy4iXHhAoGAB+mt\nPSteVRu7ZdrigEoM48brJzthuRN+wNAq4MFLDu9DpjOspcwJfEWP5ptiCITA1kFI\ne3pZNuuJjQbesqy6HoKCBKUdzX+9OqMAa5RQX2tf9GIwZbmoa1inec5TfVOZW1Se\npAbnY32QsjuXFyGV5geVI87uvBfSv/mbTj1wx4ECgYEA5crAg/fbKqAAla8JQhe0\nqH/CNJ/loS5fleCUT/vSvrQMhjBQU9MidZC20Ch3VU4jP4Thd/Nrz+/RaAnul7at\nRNzvfHvcgzqJKdbn1YZzN98vHhpH1HJKmiAqqL6Iw8W/tsdArtyyg4+83exhot6l\nXuT6X9wPwLOvq8LM1ELh8gc=\n-----END PRIVATE KEY-----\n",
"client_email": "151760407244-compute@developer.gserviceaccount.com",
"client_id": "100778741351830888979",
"auth_uri": "https://accounts.google.com/o/oauth2/auth",
"token_uri": "https://oauth2.googleapis.com/token",
"auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
"client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/151760407244-compute%40developer.gserviceaccount.com",
"universe_domain": "googleapis.com"
