[connections.postgresql]
dialect = "postgresql"
headless = true
host = "34.87.103.138"
port = "5432"
database = "New_Database"
username = "streamlit"
password = "123789"

[runner]
enforceSerializableSessionState = true
